import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Dock from "../components/Dock";
import Desktop from "../components/Desktop";
import { AppWindowProvider } from "../context/AppWindowContext";
import WindowHost from "../components/WindowHost";
import { AppearanceProvider } from "../context/AppearanceContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MacOS Next.js Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppearanceProvider>
          <AppWindowProvider>
            <main className="min-h-dvh relative">{children}</main>
            <Desktop />
            <WindowHost />
            <Dock />
          </AppWindowProvider>
        </AppearanceProvider>
      </body>
    </html>
  );
}
