import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Dock from "../components/Dock";
import { AppWindowProvider } from "../context/AppWindowContext";
import WindowHost from "../components/WindowHost";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MacOS Next.js Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pb-28`}
      >
        <AppWindowProvider>
          <main className="min-h-screen">{children}</main>
          <WindowHost />
          <Dock />
        </AppWindowProvider>
      </body>
    </html>
  );
}
